import { reactConfig } from '@schemaloom/config/eslint/react';

export default [
  // Generated by `next build` and carrying a "do not edit" banner. Its triple-slash
  // path reference is Next's, not ours, and regenerating it would undo any fix.
  { ignores: ['next-env.d.ts'] },
  ...reactConfig({ tsconfigRootDir: import.meta.dirname }),
];
