import { reactConfig } from '@schemaloom/config/eslint/react';

export default [
  // Generated by `next build` and carrying a "do not edit" banner. Its triple-slash
  // path reference is Next's, not ours, and regenerating it would undo any fix.
  { ignores: ['next-env.d.ts'] },
  // Served verbatim as static files (sw.js is a self-unregistering worker), outside
  // every tsconfig, so the typed rules cannot parse them.
  { ignores: ['public/**'] },
  ...reactConfig({ tsconfigRootDir: import.meta.dirname }),
];
