import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve as resolvePath } from 'node:path';
import {
  BUILT_IN_ROLES,
  PERMISSION_ATOMS,
  type BuiltInResourceRole,
  type OrgRole,
  type RestrictedFieldMode,
} from '@schemaloom/contracts';
import { fieldVisibility, type Field, type VisibilityContext } from '@schemaloom/schema-model';
import { describe, expect, it } from 'vitest';
import { buildSkeleton } from './cache-keys';
import {
  allAccessMap,
  atomsAt,
  canOpenProject,
  computeProjectMap,
  restrictedOkEntityIds,
  visibleEntityIds,
} from './resolve';
import {
  principalKey,
  type LiveGrant,
  type PrincipalKey,
  type ProjectPermissionMap,
  type ResourceRef,
  type Subject,
} from './types';

/**
 * Doc 05 §11.1 — THE GOLDEN MATRIX.
 *
 * Every cell is generated by the REAL resolver — `allAccessMap` / `computeProjectMap` /
 * `atomsAt`, the same pure functions `PermissionResolver` delegates to (the service adds
 * Prisma and Redis and nothing else) — and snapshotted to a COMMITTED CSV. There is no
 * second implementation of the rules here; a test that re-derives the expected answer
 * agrees with itself, not with the system.
 *
 * The point is NOT that the matrix passes today. The point is that a change to the
 * resolver arrives in review as a readable diff in
 * `apps/api/test/fixtures/permission-matrix.csv`, where a human reads "this cell went
 * from deny to allow" and asks whether that was intended. A diff with no corresponding
 * intentional change fails review, not just CI.
 *
 * Regenerate deliberately, never reflexively:
 *
 *     UPDATE_MATRIX=1 pnpm --filter @schemaloom/api test golden-matrix
 *
 * DEVIATION from §11.1, stated so nobody thinks it drifted: the doc emits all 11
 * predicates per (subject, resource) cell, which repeats `canOpenProject` and
 * `fieldVisibility(fld_sal)` eight times per subject although neither is a function of
 * the resource. One behaviour change would then surface as eight identical diff lines,
 * which is noise in exactly the artefact whose whole value is signal. They are emitted
 * once per subject with resource `-` instead. Same coverage, 2,220 rows instead of 2,640.
 */

const CSV_PATH = resolvePath(__dirname, '../../test/fixtures/permission-matrix.csv');
const CSV_HEADER = 'mode,subject,resource,predicate,result';

// ---------------------------------------------------------------------------------------
// §7.6's fixture world, verbatim.
//
//   prj_shop
//   ├── ar_bill "Billing"   ent_inv, ent_pay, ent_emp  (ent_emp holds restricted fld_sal)
//   ├── ar_cat  "Catalog"   ent_prod
//   └── (no area)           ent_aud
// ---------------------------------------------------------------------------------------

const PROJECT = 'prj_shop';
const AR_BILL = 'ar_bill';
const AR_CAT = 'ar_cat';
const ENT_EMP = 'ent_emp';
const NOW = 1_700_000_000_000;

const SKELETON = buildSkeleton(
  7,
  [AR_BILL, AR_CAT],
  [
    { id: 'ent_inv', areaId: AR_BILL },
    { id: 'ent_pay', areaId: AR_BILL },
    { id: ENT_EMP, areaId: AR_BILL },
    { id: 'ent_prod', areaId: AR_CAT },
    { id: 'ent_aud', areaId: null },
  ],
  [ENT_EMP],
);

const RESOURCES: readonly ResourceRef[] = [
  { type: 'project', id: PROJECT },
  { type: 'area', id: AR_BILL },
  { type: 'area', id: AR_CAT },
  { type: 'entity', id: 'ent_inv' },
  { type: 'entity', id: 'ent_pay' },
  { type: 'entity', id: ENT_EMP },
  { type: 'entity', id: 'ent_prod' },
  { type: 'entity', id: 'ent_aud' },
];

/** `employees.salary` — the one restricted field the 11th predicate asks about. */
const FLD_SAL: Field = {
  id: 'fld_sal',
  name: 'salary',
  version: 1,
  engineProps: {},
  entityId: ENT_EMP,
  parentFieldId: null,
  ordinal: 2,
  type: { name: 'numeric', args: [10, 2] },
  isNullable: false,
  isRestricted: true,
  isPii: false,
  isDeprecated: false,
  doc: null,
};
const FIELDS: Record<string, Field> = { [FLD_SAL.id]: FLD_SAL };

// ---------------------------------------------------------------------------------------
// The subjects. The doc's 12, plus three that widen the built-in-role and
// `field:viewRestricted` axes the task names: every one of the five built-ins appears at
// the project level, and one subject holds the restricted-field modifier.
// ---------------------------------------------------------------------------------------

interface GrantSpec {
  readonly principal: PrincipalKey;
  readonly ref: ResourceRef;
  readonly role: BuiltInResourceRole;
  readonly canUseAi?: boolean;
  readonly canViewRestricted?: boolean;
}

interface MatrixSubject {
  readonly name: string;
  /** null only for a share link: R13's org short-circuit does not apply to one. */
  readonly orgRole: OrgRole | null;
  readonly subject: Subject;
  readonly grants: readonly GrantSpec[];
}

const ANA = 'usr_ana';
const USER: Subject = { kind: 'user', userId: ANA, orgId: 'org_acme' };
const LINK: Subject = { kind: 'share_link', shareLinkId: 'sl_1', projectId: PROJECT };
const ANA_KEY = principalKey('user', ANA);
const GROUP_KEY = principalKey('group', 'grp_analysts');
const LINK_KEY = principalKey('share_link', 'sl_1');

const project = (): ResourceRef => ({ type: 'project', id: PROJECT });

const SUBJECTS: readonly MatrixSubject[] = [
  { name: 'org-owner', orgRole: 'owner', subject: USER, grants: [] },
  { name: 'org-admin', orgRole: 'admin', subject: USER, grants: [] },
  { name: 'org-member-no-grant', orgRole: 'member', subject: USER, grants: [] },
  { name: 'guest-no-grant', orgRole: 'guest', subject: USER, grants: [] },
  {
    name: 'project-viewer',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'viewer' }],
  },
  {
    name: 'project-commenter',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'commenter' }],
  },
  {
    name: 'project-documenter',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'documenter' }],
  },
  {
    name: 'project-editor-ai',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'editor', canUseAi: true }],
  },
  {
    name: 'project-manager',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'manager' }],
  },
  {
    name: 'member-viewer-restricted',
    orgRole: 'member',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: project(), role: 'viewer', canViewRestricted: true }],
  },
  {
    // SPEC workflow #2's freelancer: Billing area only, Editor.
    name: 'area-editor',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: { type: 'area', id: AR_BILL }, role: 'editor' }],
  },
  {
    name: 'entity-viewer',
    orgRole: 'guest',
    subject: USER,
    grants: [{ principal: ANA_KEY, ref: { type: 'entity', id: ENT_EMP }, role: 'viewer' }],
  },
  {
    // E1 — R15: the nearer entity grant decides, per principal, so this DEMOTES at ent_emp.
    name: 'project-editor+entity-viewer',
    orgRole: 'guest',
    subject: USER,
    grants: [
      { principal: ANA_KEY, ref: project(), role: 'editor' },
      { principal: ANA_KEY, ref: { type: 'entity', id: ENT_EMP }, role: 'viewer' },
    ],
  },
  {
    // E5 — R16: a DIFFERENT principal's narrow grant unions, it never demotes.
    name: 'project-manager+group-entity-viewer',
    orgRole: 'member',
    subject: USER,
    grants: [
      { principal: ANA_KEY, ref: project(), role: 'manager' },
      { principal: GROUP_KEY, ref: { type: 'entity', id: ENT_EMP }, role: 'viewer' },
    ],
  },
  {
    // R17 — the ceiling, whatever the link's grant says.
    name: 'share-link-viewer',
    orgRole: null,
    subject: LINK,
    grants: [{ principal: LINK_KEY, ref: project(), role: 'viewer' }],
  },
];

// ---------------------------------------------------------------------------------------
// Generation.
// ---------------------------------------------------------------------------------------

function liveGrants(specs: readonly GrantSpec[]): LiveGrant[] {
  return specs.map((spec, i) => ({
    id: `gr_${String(i)}`,
    resourceType: spec.ref.type,
    resourceId: spec.ref.id,
    principalKey: spec.principal,
    atoms: [...BUILT_IN_ROLES[spec.role]],
    canUseAi: spec.canUseAi ?? false,
    canViewRestricted: spec.canViewRestricted ?? false,
    expiresAt: null,
    linkExpiresAt: null,
  }));
}

/** `PermissionResolver.resolveProject`'s branch, minus the two I/O reads. */
function mapFor(row: MatrixSubject, mode: RestrictedFieldMode): ProjectPermissionMap {
  const { orgRole, subject } = row;
  if (orgRole === 'owner' || orgRole === 'admin') {
    return allAccessMap(PROJECT, SKELETON, subject, orgRole, mode, NOW);
  }
  const principals =
    subject.kind === 'share_link'
      ? [LINK_KEY]
      : [ANA_KEY, ...new Set(row.grants.map((g) => g.principal).filter((p) => p !== ANA_KEY))];

  return computeProjectMap({
    projectId: PROJECT,
    subject,
    orgRole,
    principals,
    grants: liveGrants(row.grants),
    skeleton: SKELETON,
    restrictedFieldMode: mode,
    nowMs: NOW,
  });
}

/**
 * The slice of `VisibilityFilter.contextFrom` that `fieldVisibility` actually reads.
 * Every value in it comes from the resolver; the three keys below are a projection, not
 * a rule.
 */
function visibilityContextFor(map: ProjectPermissionMap): VisibilityContext {
  return {
    projectId: PROJECT,
    subjectKind: 'user',
    subjectKey: map.subjectKey,
    canOpenProject: canOpenProject(map),
    visibleEntityIds: visibleEntityIds(map, SKELETON),
    restrictedOkEntityIds: restrictedOkEntityIds(map, SKELETON),
    areasWithAtoms: new Set<string>(),
    restrictedFieldMode: map.restrictedFieldMode,
    totalEntityCount: SKELETON.entities.length,
    entitiesWithRestrictedFields: SKELETON.entitiesWithRestrictedFields,
  };
}

export function generateMatrix(): string[] {
  const lines: string[] = [CSV_HEADER];

  for (const mode of ['mask', 'hide'] as const) {
    for (const row of SUBJECTS) {
      const map = mapFor(row, mode);

      for (const ref of RESOURCES) {
        const atoms = atomsAt(map, SKELETON, ref);
        for (const atom of PERMISSION_ATOMS) {
          const result = atoms.has(atom) ? 'allow' : 'deny';
          lines.push(`${mode},${row.name},${ref.id},${atom},${result}`);
        }
      }

      lines.push(`${mode},${row.name},-,canOpenProject,${String(canOpenProject(map))}`);
      const visibility = fieldVisibility(visibilityContextFor(map), FIELDS, FLD_SAL);
      lines.push(`${mode},${row.name},-,fieldVisibility(fld_sal),${visibility}`);
    }
  }
  return lines;
}

/** Only the cells that moved, so the failure message IS the review diff. */
function driftingCells(committed: readonly string[], generated: readonly string[]): string[] {
  const out: string[] = [];
  const end = Math.max(committed.length, generated.length);
  for (let i = 0; i < end && out.length < 50; i += 1) {
    if (committed[i] === generated[i]) continue;
    out.push(`row ${String(i + 1)}: was "${committed[i] ?? '<absent>'}" now "${generated[i] ?? '<absent>'}"`);
  }
  return out;
}

describe('the golden permission matrix', () => {
  const generated = generateMatrix();

  it('covers every subject x resource x atom, plus the two derived predicates', () => {
    const perSubject = RESOURCES.length * PERMISSION_ATOMS.length + 2;
    expect(generated).toHaveLength(1 + 2 * SUBJECTS.length * perSubject);
  });

  it('matches the committed CSV snapshot', () => {
    if (process.env.UPDATE_MATRIX === '1') {
      mkdirSync(dirname(CSV_PATH), { recursive: true });
      writeFileSync(CSV_PATH, `${generated.join('\n')}\n`, 'utf8');
    }
    const committed = readFileSync(CSV_PATH, 'utf8').trimEnd().split(/\r?\n/);

    expect(
      driftingCells(committed, generated),
      'The resolver now answers differently than the committed matrix. If that was ' +
        'intentional, regenerate with UPDATE_MATRIX=1 and review the CSV diff cell by cell.',
    ).toEqual([]);
  });
});
