/**
 * The DDL the §17 round-trip checks run on. Test-only: nothing exports it from `index.ts` or
 * `static.ts`, so it never reaches `dist`.
 *
 * `ECOMMERCE` is deliberately ordinary — it is the schema a user actually pastes in, not a
 * curated one. That is where round-trip bugs live: a `DEFAULT now()` followed by `NOT NULL`,
 * a foreign key to a table defined further down the file, a generated column, an enum in one
 * schema used by a table in another, an expression index, a partial index, an INCLUDE column,
 * and a view over two tables.
 *
 * `MIXED` is the report's fixture. Every statement in it is a different `ImportStatementStatus`
 * so `import/reasons-present` compares `expectNotApplied` against a real spread rather than
 * one refused trigger.
 */

export const ECOMMERCE_DDL = `
CREATE SCHEMA billing;

CREATE TYPE public.order_status AS ENUM ('pending', 'paid', 'refunded', 'void');

CREATE DOMAIN public.positive_int AS integer NOT NULL CHECK (VALUE > 0);

CREATE TABLE public.customers (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  email character varying(255) NOT NULL,
  display_name text,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  tags text[],
  CONSTRAINT customers_pkey PRIMARY KEY (id),
  CONSTRAINT customers_email_key UNIQUE (email)
);

CREATE TABLE public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  customer_id bigint NOT NULL,
  status public.order_status DEFAULT 'pending' NOT NULL,
  quantity public.positive_int,
  total numeric(12,2) NOT NULL,
  net_total numeric(12,2) GENERATED ALWAYS AS (total * 0.9) STORED,
  placed_at timestamp with time zone DEFAULT now() NOT NULL,
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_total_positive CHECK (total > 0)
);

CREATE TABLE public.order_lines (
  order_id bigint NOT NULL,
  line_no integer NOT NULL,
  sku text NOT NULL,
  unit_price numeric(12,2) NOT NULL,
  CONSTRAINT order_lines_pkey PRIMARY KEY (order_id, line_no)
);

ALTER TABLE public.orders
  ADD CONSTRAINT orders_customer_id_fkey FOREIGN KEY (customer_id)
  REFERENCES public.customers (id) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE public.order_lines
  ADD CONSTRAINT order_lines_order_id_fkey FOREIGN KEY (order_id)
  REFERENCES public.orders (id) ON DELETE CASCADE;

CREATE INDEX orders_customer_id_idx ON public.orders USING btree (customer_id, placed_at DESC) INCLUDE (total);

CREATE INDEX orders_open_idx ON public.orders USING btree (placed_at) WHERE total > 0;

CREATE UNIQUE INDEX customers_email_lower_idx ON public.customers USING btree (lower(email));

CREATE VIEW billing.order_summary AS SELECT id, customer_id, total FROM public.orders;
`;

export const MIXED_DDL = `
SET search_path TO public;

BEGIN;

CREATE TABLE public.invoices (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  amount numeric(12,2) NOT NULL,
  CONSTRAINT invoices_pkey PRIMARY KEY (id)
);

-- Understood, deliberately not modelled.
CREATE TRIGGER invoices_audit AFTER INSERT ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION audit_row();

-- Understood, re-applied by the docs module rather than the schema model.
COMMENT ON TABLE public.invoices IS 'One row per invoice';

-- Represented with loss: EXCLUDE has no place in the IR.
ALTER TABLE public.invoices
  ADD CONSTRAINT invoices_no_overlap EXCLUDE USING gist (amount WITH =);

-- Cannot be parsed at all.
CREATE TABL typo (id int);

COMMIT;
`;
