import { renderStatements, type ExportOptions, type ExportResult } from '@schemaloom/engine-sdk';
import type { RedactedModel } from '@schemaloom/schema-model';
import { describe, expect, it } from 'vitest';
import { CONFORMANCE_FIXTURES, referenceModel } from './conformance-fixtures.js';
import { EXPORTER } from './exporter.js';
import { column, fullyVisible, model, ns, table } from './fixture-model.js';
import { quoteDocText, quoteIdentifier } from './sql-text.js';

/**
 * Doc 03 §10, from the side the conformance suite cannot reach: the suite asserts the
 * PROPERTIES (deterministic, ordered, announced) over whatever fixtures an engine supplies;
 * this file asserts the DDL PostgreSQL actually needs.
 */

const OPTIONS: ExportOptions = {
  format: 'ddl',
  includeComments: true,
  includeDrops: false,
  includeIfNotExists: false,
  engineOptions: {},
};

function exportModel(
  redacted: RedactedModel,
  overrides: Partial<ExportOptions> = {},
): Promise<ExportResult> {
  return EXPORTER.export({
    model: redacted,
    options: { ...OPTIONS, ...overrides },
    context: { projectId: 'p1', serverVersion: '16' },
  });
}

const reference = (): RedactedModel => fullyVisible(referenceModel());

describe('determinism', () => {
  it('produces byte-identical output on repeated runs', async () => {
    const runs = await Promise.all([
      exportModel(reference()),
      exportModel(reference()),
      exportModel(reference()),
    ]);
    const [first] = runs;
    for (const run of runs) expect(renderStatements(run)).toBe(renderStatements(first));
  });

  it('is unchanged when the objects arrive in a different insertion order', async () => {
    const straight = await exportModel(reference());

    // Reverse every map. `Object.keys` order is the only ordering an IR has, so an exporter
    // that leans on it fails here and nowhere else.
    const base = referenceModel();
    const reversed = fullyVisible({
      ...base,
      objects: {
        area: base.objects.area,
        namespace: Object.fromEntries(Object.entries(base.objects.namespace).reverse()),
        customType: Object.fromEntries(Object.entries(base.objects.customType).reverse()),
        entity: Object.fromEntries(Object.entries(base.objects.entity).reverse()),
        field: Object.fromEntries(Object.entries(base.objects.field).reverse()),
        constraint: Object.fromEntries(Object.entries(base.objects.constraint).reverse()),
        index: Object.fromEntries(Object.entries(base.objects.index).reverse()),
        link: Object.fromEntries(Object.entries(base.objects.link).reverse()),
      },
    });

    expect(renderStatements(await exportModel(reversed))).toBe(renderStatements(straight));
  });
});

describe('the stable ordering contract (§10.1)', () => {
  it('emits namespaces, then types, then entities, then constraints, then indexes', async () => {
    const result = await exportModel(reference());
    const phases = [...new Set(result.statements.map((s) => s.phase))];
    expect(phases).toEqual([
      'namespaces',
      'custom-types',
      'entities',
      'constraints',
      'indexes',
      'comments',
    ]);
  });

  it('puts a table before the view that selects from it, and that view before its own dependant', async () => {
    const result = await exportModel(reference());
    const order = result.statements.filter((s) => s.phase === 'entities').map((s) => s.target?.id);
    expect(order.indexOf('en_orders')).toBeLessThan(order.indexOf('en_summary'));
    // `order_stats` selects from `order_summary` — §10.1's "a view before a view that
    // selects from *it*", which a phase order alone does not give you.
    expect(order.indexOf('en_summary')).toBeLessThan(order.indexOf('en_stats'));
  });

  it('numbers statements 0..n-1 with no gaps', async () => {
    const result = await exportModel(reference());
    expect(result.statements.map((s) => s.ordinal)).toEqual(result.statements.map((_, i) => i));
  });

  it('drops in reverse dependency order, so a dependent view goes first', async () => {
    const result = await exportModel(reference(), { includeDrops: true });
    const drops = result.statements.filter((s) => s.phase === 'drops').map((s) => s.target?.id);
    expect(drops.indexOf('en_stats')).toBeLessThan(drops.indexOf('en_summary'));
    expect(drops.indexOf('en_summary')).toBeLessThan(drops.indexOf('en_orders'));
  });
});

describe('the DDL itself', () => {
  it('renders a table with its types, defaults, identity and generated columns', async () => {
    const result = await exportModel(reference());
    const orders = result.statements.find(
      (s) => s.target?.id === 'en_orders' && s.phase === 'entities',
    );
    expect(orders?.text).toContain('CREATE TABLE public.orders');
    expect(orders?.text).toContain('id integer GENERATED BY DEFAULT AS IDENTITY NOT NULL');
    expect(orders?.text).toContain('total numeric(12,2)');
    expect(orders?.text).toContain(
      'net_total numeric(12,2) GENERATED ALWAYS AS (total * 0.9) STORED',
    );
    expect(orders?.text).toContain('TABLESPACE fast_ssd');
  });

  it('qualifies a user-defined type that lives in another schema', async () => {
    const base = referenceModel();
    const enumType = base.objects.customType.ct_status;
    expect(enumType).toBeDefined();
    const moved = fullyVisible({
      ...base,
      objects: {
        ...base.objects,
        customType: {
          ...base.objects.customType,
          ct_status: { ...enumType!, namespaceId: 'ns_billing' },
        },
      },
    });
    const result = await exportModel(moved);
    const orders = result.statements.find(
      (s) => s.target?.id === 'en_orders' && s.phase === 'entities',
    );
    // Unqualified, this compiles only if `billing` happens to be on the search_path.
    expect(orders?.text).toContain('status billing.order_status');
  });

  it('emits foreign keys and constraints as ALTER TABLE, after every table exists', async () => {
    const result = await exportModel(reference());
    const fk = result.statements.find((s) => s.target?.id === 'ln_fk_orders_customer');
    expect(fk?.text).toBe(
      'ALTER TABLE public.orders ADD CONSTRAINT orders_customer_id_fkey ' +
        'FOREIGN KEY (customer_id) REFERENCES public.customers (id) ' +
        'ON DELETE RESTRICT ON UPDATE CASCADE',
    );
  });

  it('renders an expression index with its predicate, and an INCLUDE payload', async () => {
    const result = await exportModel(reference());
    const expression = result.statements.find((s) => s.target?.id === 'ix_orders_status_expr');
    expect(expression?.text).toBe(
      'CREATE INDEX orders_status_lower_idx ON public.orders USING btree ' +
        '((lower(status::text))) WHERE total > 0',
    );
    const include = result.statements.find((s) => s.target?.id === 'ix_orders_customer');
    expect(include?.text).toContain('INCLUDE (total)');
  });

  it('adds IF NOT EXISTS where PostgreSQL accepts it, and only when asked', async () => {
    const guarded = await exportModel(reference(), { includeIfNotExists: true });
    const text = (id: string): string =>
      guarded.statements.find((s) => s.target?.id === id && s.phase !== 'comments')?.text ?? '';
    expect(text('ns_billing')).toContain('CREATE SCHEMA IF NOT EXISTS billing');
    expect(text('en_orders')).toContain('CREATE TABLE IF NOT EXISTS public.orders');
    // `CREATE VIEW IF NOT EXISTS` is not PostgreSQL syntax, so the flag does not reach it.
    expect(text('en_summary')).toContain('CREATE VIEW billing.order_summary');

    const plain = await exportModel(reference());
    expect(renderStatements(plain)).not.toContain('IF NOT EXISTS');
  });

  it('quotes only what PostgreSQL would otherwise misread', () => {
    expect(quoteIdentifier('orders')).toBe('orders');
    expect(quoteIdentifier('Orders')).toBe('"Orders"');
    expect(quoteIdentifier('order')).toBe('"order"'); // reserved
    expect(quoteIdentifier('two words')).toBe('"two words"');
    expect(quoteIdentifier('a"b')).toBe('"a""b"');
  });
});

describe('COMMENT ON (§10.2)', () => {
  it('emits one comment per documented object, and none for the undocumented', async () => {
    const result = await exportModel(reference());
    const comments = result.statements.filter((s) => s.phase === 'comments');
    expect(comments.map((s) => s.target?.id).sort()).toEqual(['en_orders', 'fd_ord_status']);
    expect(comments.find((s) => s.target?.id === 'fd_ord_status')?.text).toBe(
      "COMMENT ON COLUMN public.orders.status IS 'Where the order is in the payment lifecycle'",
    );
  });

  it('dollar-quotes a comment body containing an apostrophe', async () => {
    const result = await exportModel(reference());
    const table_ = result.statements.find(
      (s) => s.phase === 'comments' && s.target?.id === 'en_orders',
    );
    expect(table_?.text).toBe(
      "COMMENT ON TABLE public.orders IS $doc$Every customer's orders, one row per order$doc$",
    );
    // The tag widens rather than colliding, deterministically.
    expect(quoteDocText("it's $doc$ here")).toBe("$doc1$it's $doc$ here$doc1$");
  });

  it('omits the whole phase when the caller did not ask for comments', async () => {
    const result = await exportModel(reference(), { includeComments: false });
    expect(result.statements.filter((s) => s.phase === 'comments')).toEqual([]);
  });

  it('emits nothing for an object with no doc', async () => {
    const plain = fullyVisible(
      model({
        namespaces: [ns({ id: 'n1', name: 'public', isDefault: true })],
        entities: [table({ id: 'e1', name: 't', namespaceId: 'n1' })],
        fields: [column({ id: 'f1', name: 'c', entityId: 'e1' })],
      }),
    );
    const result = await exportModel(plain);
    expect(result.statements.filter((s) => s.phase === 'comments')).toEqual([]);
  });
});

describe('exporting a redacted model (§10.3)', () => {
  const redacted = CONFORMANCE_FIXTURES.redactedModel;

  it('announces the omission once, without counting it', async () => {
    const result = await exportModel(redacted);
    expect(result.incomplete).toBe(true);
    const header = result.statements.filter((s) => s.phase === 'header');
    expect(header).toHaveLength(1);
    expect(header[0]?.text).toBe('-- Some objects are not included because of your access level.');
    // No count, no names — doc 05 §8.4 L8: an aggregate over hidden objects IS the leak.
    expect(header[0]?.text).not.toMatch(/\d/);
    expect(result.diagnostics).toEqual([]);
  });

  it('emits no column with a blank name or a blank type', async () => {
    const result = await exportModel(redacted);
    const ddl = renderStatements(result);
    // A masked field is `name: '', type: { name: '' }` (punch-list ∆4). Emitting it by name
    // and type is what §10.3 rule 2 reverses.
    expect(ddl).not.toContain('""');
    expect(ddl).not.toMatch(/^\s+\S*\s*,?\s*$/m);
  });

  it('skips the stub entity, and the foreign key that points at it', async () => {
    const result = await exportModel(redacted);
    const targets = new Set(result.statements.map((s) => s.target?.id));
    expect(targets.has('en_customers')).toBe(false);
    expect(targets.has('ln_fk_orders_customer')).toBe(false);
    // …while the table the viewer CAN see is still exported.
    expect(targets.has('en_orders')).toBe(true);
  });

  it('exports a propsRedacted object without its engineProps, rather than dropping it', async () => {
    const orders = redacted.objects.entity.en_orders;
    expect(orders?.propsRedacted).toBe(true);
    expect(orders?.restricted).toBeUndefined();

    const result = await exportModel(redacted);
    const statement = result.statements.find(
      (s) => s.phase === 'entities' && s.target?.id === 'en_orders',
    );
    // R-1's point: `propsRedacted` is orthogonal to `restricted`. Treating it as a grade of
    // restriction would DELETE a table the viewer is allowed to see.
    expect(statement?.text).toContain('CREATE TABLE public.orders');
    expect(statement?.text).not.toContain('TABLESPACE');
  });

  it('is complete, with no header, when nothing was hidden', async () => {
    const result = await exportModel(reference());
    expect(result.incomplete).toBe(false);
    expect(result.statements.filter((s) => s.phase === 'header')).toEqual([]);
  });
});

describe('renderStatements', () => {
  it('joins with the separator and puts a blank line between phases', async () => {
    const result = await exportModel(reference());
    expect(result.separator).toBe(';');
    const text = renderStatements(result);
    expect(
      text
        .split('\n')
        .filter((line) => line.trim() !== '')
        .at(-1),
    ).toMatch(/;$/);
    expect(text).toContain('\n\n');
  });

  it('can label the phases', async () => {
    const result = await exportModel(reference());
    expect(renderStatements(result, { phaseHeadings: true })).toContain('-- entities');
  });
});
